### ISSUE TITLE
PySpark入门的数据集链接无效404

### ISSUE THREAD

**Issue by BruceChen2017** [IBM/developer_zh#3]
[PySpark入门](https://developer.ibm.com/zh/technologies/analytics/tutorials/getting-started-with-pyspark)的数据集链接无效，返回404，数据集原始链接可在原文[Getting started with PySpark](https://developer.ibm.com/technologies/analytics/tutorials/getting-started-with-pyspark/)找到

**Comment by xchenibm** [comment]
您好，
感谢您的反馈。链接现在可以正常访问了。
